name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - requests=2.24.0
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - pip:
      - wandb==0.15.3
      - git+https://github.com/gchristodo/build-ml-pipeline-for-short-term-rental-prices#egg=wandb-utils&subdirectory=components
