name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.14.1
  - pyyaml=5.3.1
  - hydra-core=1.0.6
  - pip=20.3.3
  - pyarrow=8.0.0
  - pip:
      - wandb==0.15.3
      - fastparquet==2023.4.0