name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
  - pip=20.3.3
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - pip:
      - wandb==0.15.3
      - git+https://github.com/gchristodo/build-ml-pipeline-for-short-term-rental-prices#egg=wandb-utils&subdirectory=components/test_regression_model
