name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - pandas=1.2.3
  - pip:
      - wandb==0.15.3
      - git+https://github.com/gchristodo/build-ml-pipeline-for-short-term-rental-prices#egg=wandb-utils&subdirectory=src
